import { useEffect, useState } from 'react';
import { api } from '../api';

type Props = { token: string; onMessage: (message: string) => void };
export function ProfileDeadlinePanel({ token, onMessage }: Props) {
  const [profile, setProfile] = useState<any>(); const [eligibility, setEligibility] = useState<any>(); const [reports, setReports] = useState<any[]>([]); const [fullName, setFullName] = useState(''); const [phone, setPhone] = useState(''); const [className, setClassName] = useState('');
  useEffect(() => { const headers = { headers: { Authorization: `Bearer ${token}` } }; void Promise.all([api.get('/users/me', headers), api.get('/users/me/eligibility', headers), api.get('/progress/reports', headers)]).then(([profileResponse, eligibilityResponse, reportResponse]) => { const next = profileResponse.data.data; setProfile(next); setFullName(next.fullName); setPhone(next.phone ?? ''); setClassName(next.studentProfile?.className ?? ''); setEligibility(eligibilityResponse.data.data); setReports(reportResponse.data.data); }).catch(() => undefined); }, [token]);
  async function update() { try { await api.patch('/users/me', { fullName, phone, className }, { headers: { Authorization: `Bearer ${token}` } }); onMessage('Đã cập nhật hồ sơ.'); } catch (error: any) { onMessage(error.response?.data?.message ?? 'Không thể cập nhật hồ sơ.'); } }
  return <section className="panel workflow-panel"><div className="panel-title"><h3>Hồ sơ & điều kiện KLTN</h3><span>{eligibility?.eligible ? 'Đủ điều kiện' : 'Cần bổ sung'}</span></div><div className="workflow-form"><input value={fullName} onChange={(event) => setFullName(event.target.value)} placeholder="Họ và tên" /><input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="Số điện thoại" /><input value={className} onChange={(event) => setClassName(event.target.value)} placeholder="Lớp" /><button onClick={update}>Lưu hồ sơ</button></div><p className="status-line"><span>{profile?.studentProfile?.studentCode ?? profile?.email}</span><span className="status">{eligibility?.eligible ? 'Đủ điều kiện đăng ký' : (eligibility?.reasons ?? []).join('; ')}</span></p><div className="deadline-list">{reports.filter((report) => report.dueAt).map((report) => <p className="status-line" key={report.id}><span>{report.title}</span><span>Hạn: {new Date(report.dueAt).toLocaleDateString('vi-VN')}</span></p>)}{!reports.some((report) => report.dueAt) && <small>Chưa có deadline báo cáo được cấu hình.</small>}</div></section>;
}
