import { useEffect, useState } from 'react';
import { api } from '../api';
import { useAuthStore } from '../store';
import { io } from 'socket.io-client';
import { AdminWorkflowPanel } from './AdminWorkflowPanel';
import { ProfileDeadlinePanel } from './ProfileDeadlinePanel';

type Item = Record<string, any>;
const auth = (token: string) => ({ headers: { Authorization: `Bearer ${token}` } });

export function WorkflowPanels() {
  const { accessToken, user } = useAuthStore(); const token = accessToken ?? ''; const role = user?.role || user?.roles?.[0] || 'SINH_VIEN';
  const [groups, setGroups] = useState<Item[]>([]); const [appointments, setAppointments] = useState<Item[]>([]); const [notifications, setNotifications] = useState<Item[]>([]); const [evidence, setEvidence] = useState<Item[]>([]); const [committees, setCommittees] = useState<Item[]>([]); const [message, setMessage] = useState('');
  async function refresh() { const [groupResponse, appointmentResponse, notificationResponse, evidenceResponse, committeeResponse] = await Promise.all([api.get('/progress/groups', auth(token)), api.get('/appointments', auth(token)), api.get('/notifications', auth(token)), role === 'SINH_VIEN' ? api.get('/evidence', auth(token)) : Promise.resolve({ data: { data: [] } }), (role === 'TRUONG_BO_MON' || role === 'QUAN_LY_BO_MON') ? api.get('/defense/committees', auth(token)) : Promise.resolve({ data: { data: [] } })]); setGroups(groupResponse.data.data); setAppointments(appointmentResponse.data.data); setNotifications(notificationResponse.data.data.items ?? notificationResponse.data.data); setEvidence(evidenceResponse.data.data); setCommittees(committeeResponse.data.data); }
  useEffect(() => { if (token) void refresh(); }, [token]);
  useEffect(() => {
    if (!token || !user?.id) return undefined;
    const socket = io(`${import.meta.env.VITE_API_URL?.replace(/\/api$/, '') ?? 'http://localhost:3000'}/notifications`, { withCredentials: true });
    socket.on('notification', (notification: Item) => setNotifications((items) => [notification, ...items.filter((item) => item.id !== notification.id)]));
    socket.emit('join', user.id);
    return () => { socket.disconnect(); };
  }, [token, user?.id]);
  return <section className="workflow-panels"><ProfileDeadlinePanel token={token} onMessage={setMessage} /><NotificationPanel token={token} items={notifications} onRefresh={refresh} /><AppointmentPanel token={token} groups={groups} items={appointments} onRefresh={refresh} onMessage={setMessage} />{role === 'SINH_VIEN' && <><SubmissionPanel token={token} groups={groups} onMessage={setMessage} /><EvidencePanel token={token} items={evidence} onRefresh={refresh} onMessage={setMessage} /></>}{(role === 'TRUONG_BO_MON' || role === 'QUAN_LY_BO_MON') && <AdminWorkflowPanel token={token} groups={groups} committees={committees} onMessage={setMessage} />}{message && <p className="notice">{message}</p>}</section>;
}

function NotificationPanel({ token, items, onRefresh }: { token: string; items: Item[]; onRefresh: () => void }) { async function read(id: string) { await api.patch(`/notifications/${id}/read`, {}, auth(token)); onRefresh(); } return <section className="panel workflow-panel"><div className="panel-title"><h3>Thông báo</h3><span>{items.filter((item) => !item.readAt).length} chưa đọc</span></div><div className="notification-list">{items.slice(0, 8).map((item) => <button className={item.readAt ? 'notification read' : 'notification'} key={item.id} onClick={() => read(item.id)}><strong>{item.title}</strong><span>{item.message}</span><small>{new Date(item.createdAt).toLocaleString('vi-VN')}</small></button>)}</div></section>; }

function AppointmentPanel({ token, groups, items, onRefresh, onMessage }: { token: string; groups: Item[]; items: Item[]; onRefresh: () => void; onMessage: (value: string) => void }) { const [groupId, setGroupId] = useState(''); const [guestId, setGuestId] = useState(''); const [title, setTitle] = useState('Trao đổi KLTN'); const [mode, setMode] = useState('ONLINE'); const [startsAt, setStartsAt] = useState(''); const [endsAt, setEndsAt] = useState(''); async function create() { try { await api.post('/appointments', { groupId, guestId: guestId || undefined, title, mode, startsAt: new Date(startsAt).toISOString(), endsAt: new Date(endsAt).toISOString() }, auth(token)); onMessage('Đã đề xuất lịch hẹn.'); onRefresh(); } catch (error: any) { onMessage(error.response?.data?.message ?? 'Không thể tạo lịch hẹn.'); } } async function update(id: string, status: string) { await api.patch(`/appointments/${id}/status`, { status }, auth(token)); onRefresh(); } return <section className="panel workflow-panel"><div className="panel-title"><h3>Lịch hẹn</h3><span>{items.length} lịch</span></div><div className="workflow-form"><select value={groupId} onChange={(event) => setGroupId(event.target.value)}><option value="">Chọn nhóm</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name || group.code}</option>)}</select><input placeholder="Guest user ID" value={guestId} onChange={(event) => setGuestId(event.target.value)} /><input value={title} onChange={(event) => setTitle(event.target.value)} /><select value={mode} onChange={(event) => setMode(event.target.value)}><option value="ONLINE">Online</option><option value="OFFLINE">Offline</option></select><input type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} /><input type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} /><button onClick={create}>Đề xuất lịch</button></div><div className="appointment-list">{items.map((item) => <article key={item.id}><strong>{item.title}</strong><span>{new Date(item.startsAt).toLocaleString('vi-VN')} · {item.status}</span>{item.status === 'PROPOSED' && <button onClick={() => update(item.id, 'CONFIRMED')}>Xác nhận</button>}</article>)}</div></section>; }

function SubmissionPanel({ token, groups, onMessage }: { token: string; groups: Item[]; onMessage: (value: string) => void }) { const [groupId, setGroupId] = useState(''); const [semesterId, setSemesterId] = useState(''); const [title, setTitle] = useState('Báo cáo tiến độ'); const [reportType, setReportType] = useState('PROGRESS'); const [reportId, setReportId] = useState(''); const [file, setFile] = useState<File>(); async function createReport() { try { const response = await api.post('/progress/reports', { groupId, semesterId, title, reportType }, auth(token)); setReportId(response.data.data.id); onMessage('Đã tạo mốc báo cáo, hãy chọn tệp để nộp.'); } catch (error: any) { onMessage(error.response?.data?.message ?? 'Không thể tạo báo cáo.'); } } async function submit() { if (!reportId || !file) return onMessage('Chọn báo cáo và tệp trước khi nộp.'); const data = new FormData(); data.append('file', file); try { await api.post(`/progress/reports/${reportId}/submissions`, data, { headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'multipart/form-data' } }); onMessage('Đã nộp tài liệu.'); } catch (error: any) { onMessage(error.response?.data?.message ?? 'Không thể nộp tài liệu.'); } } return <section className="panel workflow-panel"><div className="panel-title"><h3>Nộp báo cáo & tài liệu</h3><span>{reportId ? `Report ${reportId.slice(0, 8)}` : 'Tạo mốc mới'}</span></div><div className="workflow-form"><select value={groupId} onChange={(event) => setGroupId(event.target.value)}><option value="">Chọn nhóm</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name || group.code}</option>)}</select><input placeholder="Semester ID" value={semesterId} onChange={(event) => setSemesterId(event.target.value)} /><input value={title} onChange={(event) => setTitle(event.target.value)} /><select value={reportType} onChange={(event) => setReportType(event.target.value)}><option value="PROGRESS">Tiến độ</option><option value="MIDTERM">Giữa kỳ</option><option value="FINAL">Cuối kỳ</option><option value="SOURCE_CODE">Mã nguồn</option></select><button onClick={createReport}>Tạo mốc báo cáo</button><input type="file" accept=".pdf,.doc,.docx,.pptx,.zip" onChange={(event) => setFile(event.target.files?.[0])} /><button onClick={submit}>Nộp tệp</button></div></section>; }

function EvidencePanel({ token, items, onRefresh, onMessage }: { token: string; items: Item[]; onRefresh: () => void; onMessage: (value: string) => void }) { const [title, setTitle] = useState('Minh chứng NCKH'); const [description, setDescription] = useState(''); const [file, setFile] = useState<File>(); async function submit() { const data = new FormData(); data.append('title', title); data.append('description', description); if (file) data.append('file', file); try { await api.post('/evidence', data, { headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'multipart/form-data' } }); onMessage('Đã nộp minh chứng.'); onRefresh(); } catch (error: any) { onMessage(error.response?.data?.message ?? 'Không thể nộp minh chứng.'); } } return <section className="panel workflow-panel"><div className="panel-title"><h3>Minh chứng NCKH</h3><span>{items.length} hồ sơ</span></div><div className="workflow-form"><input value={title} onChange={(event) => setTitle(event.target.value)} /><input placeholder="Mô tả" value={description} onChange={(event) => setDescription(event.target.value)} /><input type="file" onChange={(event) => setFile(event.target.files?.[0])} /><button onClick={submit}>Nộp minh chứng</button></div>{items.map((item) => <p className="status-line" key={item.id}><span>{item.title}</span><span className="status">{item.status}</span></p>)}</section>; }
